//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniTalk {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"历史消息保存数\":30,\"消息发送时间提示间隔\":5,\"快捷截图\":true}")]
        public string 常规设置 {
            get {
                return ((string)(this["常规设置"]));
            }
            set {
                this["常规设置"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"保存路径\":\"C:\\\\Program Files\\\\MiniTalk\\\\DownLoad\",\"下载完毕后自动打开文件\":false,\"屏蔽所有文件消息\":fa" +
            "lse,\"文件接收大小最大上限\":5120,\"屏蔽的后缀名\":[]}")]
        public string 传输设置 {
            get {
                return ((string)(this["传输设置"]));
            }
            set {
                this["传输设置"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"提醒类别_文本消息\":true,\r\n\"提醒类别_文件消息\":true,\r\n\"提醒类别_图片消息\":true,\r\n\"提醒类别_事件消息\":true,\r\n\"群消息" +
            "提醒\":true,\r\n\"群消息红点标注\":true,\r\n\"置顶者强提醒\":false,\r\n\"右下角浮动提醒\":false,\r\n\"强提醒模式_对话框\":true," +
            "\r\n\"强提醒模式_托盘消息\":false,\r\n\"悬浮提醒_公共会话悬浮提醒\":true,\r\n\"悬浮提醒_用户消息悬浮提醒\":true\r\n}")]
        public string 提醒设置 {
            get {
                return ((string)(this["提醒设置"]));
            }
            set {
                this["提醒设置"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"备注表\":[],\"黑名单\":[]}")]
        public string 用户管理 {
            get {
                return ((string)(this["用户管理"]));
            }
            set {
                this["用户管理"] = value;
            }
        }
    }
}
